
import dash_html_components as html

layout = html.Div([
    html.H1('Electricity Usage In India', style={"textAlign": "center"}),

    html.Div([
        html.H3('Introduction', style={"textAlign": "left"}),
        html.P('India is the world\'s third-largest producer and third-largest consumer of electricity. The national '
               'electric grid in India has an installed capacity of 370.106 GW as of 31 March 2020. '
               'Renewable power plants, which also include large hydroelectric plants, constitute 35.86% of India\'s '
               'total installed capacity. During the 2018-19 fiscal year, the gross electricity generated by '
               'utilities in India was 1,372 TWh and the total electricity generation (utilities and non-utilities) '
               'in the country was 1,547 TWh. The gross electricity consumption in 2018-19 was 1,181 kWh per capita.'),

        html.P("In 2015-16, electric energy consumption in agriculture was recorded as being the highest (17.89%) "
               "worldwide. The per capita electricity consumption is low compared to most other countries despite "
               "India having a low electricity tariff. In light of the recent COVID-19 situation, when everyone has "
               "been under lockdown for the months of April & May the impacts of the lockdown on economic activities "
               "have been faced by every sector in a positive or a negative way.With the electricity consumption "
               "being so crucial to the country, we came up with a plan to study the impact on energy consumption "
               "state and region wise."),

        html.H3('Why it is required?'),
        html.P('The current we receive in our house is AC current. As it is generated in distant places from the '
               'actual region of consumption,  We increase the voltage of the current. It passes through the '
               'transmission substation,distribution substation,transformer and then out house.The transformer '
               'reduces the Voltage and distributes it to our houses. The connected  power stations is called the '
               'power grid.  This helps in transmitting current to large distances , like from Punjab to Tamil Nadu. '
               'To maintain 50 Hz in India, the turbines in power plants has to rotate in 1500 RPM. Also the power '
               'produces must be the power consumed too. The power consumption before lock down was 161 GW and after '
               'lock down is 135GW. So if we predict a wrong power requirement there would be black out in many parts '
               'of India.  So its is required for us to predict power requirement')

    ])

])